# Generated by Django 3.1.7 on 2021-03-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=150)),
                ('fill_type', models.CharField(choices=[('cl', 'Color'), ('gradiend', 'Gradiend')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='api.area')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='api.area')),
            ],
        ),
    ]
