# Generated by Django 3.1.7 on 2021-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_area_fill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='fill_type',
            field=models.CharField(choices=[('color', 'Color'), ('gradient', 'Gradiend')], default='color', max_length=50),
            preserve_default=False,
        ),
    ]
