# Generated by Django 3.1.7 on 2021-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_color_fill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='angle',
            field=models.FloatField(default=45),
            preserve_default=False,
        ),
    ]
